<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.xeoscript.spring</groupId>
        <artifactId>spa-auth-module-parent</artifactId>
        <version>2.7.13</version>
    </parent>

    <groupId>com.xeoscript</groupId>
    <artifactId>rbl-spa-auth-lib</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>SPA Auth Lib for RBL Bank</name>

    <dependencies>

        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-saml2-service-provider</artifactId>
        </dependency>
    </dependencies>
</project>
